### PR TITLE
create array to contain tags in user controller

### PR DESCRIPTION
**Pull request by ZonyLaw**
I created an array in the user controller to contain all the tags. This array can be used in the html to produce the list.

image

### CODE REVIEW

**Comment by fservignat** [comment]
This is for the profile page ?
I'd see more something smaller 
image

Also there is twice "textile and fibre"

**Comment by ZonyLaw** [comment]
Ok...I look into it tonight.

**Comment by ZonyLaw** [comment]
here is the revised version...still need some of your frontend magic. Happy for you to merge.

image

**Comment by fservignat** [comment]
Perfect much better and more homogeneous with the rest of the website now. Im mergin this one and mines

**Pull request merged**
