### PR TITLE
Create map

### PR DESCRIPTION
**Pull request by KylianJanssens**
image
The map is working.
The icon is customized but didn't really had an idea what marker to use. currently it is a hammer. 
If anyone has a suggestion give a shout.

### CODE REVIEW

**Comment by fservignat** [comment]
Good job, did you also place it correctly in the pages?

**Comment by KylianJanssens** [comment]
@fservignat 
so far only at the index page. -> some styling need to be done here since it is covering currently 100% of the screenwidth but i need a TA for that.  

I still have some work to do in the show page i guess this will be my focus for tomorrow.

**Comment by fservignat** [comment]
Ok I'll do the CSS for the map, it shoudlnt take long. Is it ok to merge?

**Comment by KylianJanssens** [comment]
i think it's ok. dont forget to do a bundle install after the merge

**Comment by fservignat** [comment]
I realize you didnt use a partial to put the code of the map inside. Since we use the map on many pages, i think it should be a good idea, isnt it?

**Comment by KylianJanssens** [comment]
yeah your right! i'll do that tomorrow

**Comment by KylianJanssens** [comment]
I also need to give you guys my api key tomorrow

**Comment by KylianJanssens** [comment]
@fservignat @ZonyLaw 
ready to merge.

**Comment by fservignat** [comment]
Ok merging

**Pull request merged**
